#ifndef __types_included
#define __types_included

typedef short int word;
typedef long int dword;
typedef char byte;
typedef short int WORD;
typedef long int DWORD;
typedef char BYTE;

typedef short int bits16;
typedef long int bits32;
typedef short int BITS16;
typedef long int BITS32;

typedef unsigned long ul;
typedef unsigned short us;
typedef unsigned char uc;
typedef unsigned int ui;

#endif
